[package]
name = "rtfw_http"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4.40"
log = "0.4.26"
mime_guess = "2.0.5"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"
